  # os.system("pip install --upgrade pip")
                # os.system("python main.py")
                # os.system("start chrome")
                # os.system("taskkill /im chrome.exe")
                # os.system("start google")
                # os.system("start download")
                # os.system("start volume")
                # os.system("start brightness")
                # os.system("start settings")
                # os.system("start configure")
                # os.system("start wifi")